Fixup for compilation on boost 1.57
In boost 1.57 the + and - operations are no longer overloaded on the iterator
constants by default causing the following error:

   .../include/valijson/validation_visitor.hpp:930:76:
   error: no match for â€˜operator-â€™ (operand types are â€˜const const_iterator {aka const valijson::adapters::RapidJsonArrayValueIterator}â€™ and â€˜intâ€™)
         const typename AdapterType::Array::const_iterator secondLast = end - 1;

The ++ operator is still valid, so here we rework in terms of it.